global:
  scrape_interval:     1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.



  query_log_file: <lo file location>

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - <Alertmanager_node_name>:<port>

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - <file location>
  

scrape_configs:
  - job_name: 'prometheus'
  
    static_configs:
    - targets: [
    			<node_name>:<port>
               ]
    basic_auth:
      username: <Username>
      password: <Password>

