{
 "title": "localhost",
 "tags": [
  "canon",
  "ae"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"localhost:9100\"},cpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory consumption including Cached memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{instance=\"localhost:9100\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\"}) / node_memory_MemTotal_bytes{instance=\"localhost:9100\"} * 100",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Memory consumption excluding Cached memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{instance=\"localhost:9100\"} - (node_memory_MemFree_bytes{instance=\"localhost:9100\"} + node_memory_Buffers_bytes{instance=\"localhost:9100\"} + node_memory_Cached_bytes{instance=\"localhost:9100\"})) / node_memory_MemTotal_bytes{instance=\"localhost:9100\"}) * 100",
       "legendFormat": "canon-ae-01"
      }
     ]
    }
   ]
  },
  {
   "title": "System Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus KeepAlive Status",
     "type": "gauge",
     "description": "Health Probe of the Prometheus keepalive Status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"localhost:9100\"}",
       "legendFormat": "gbt-cass-11"
      }
     ]
    },
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"localhost:9100\"} - node_boot_time_seconds{instance=\"localhost:9100\"}",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Virtual CPUs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode=\"user\", instance=\"localhost:9100\"})",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Total Memory(RAM)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(node_memory_MemTotal_bytes{instance=\"localhost:9100\"} /1024/1024/1024,1)",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Root volume(/)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(node_filesystem_size_bytes{instance=\"localhost:9100\",mountpoint=\"/\"} /1024/1024/1024,1)",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "ebs volume(/ebs)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(node_filesystem_size_bytes{instance=\"localhost:9100\",mountpoint=\"/ebs\"} /1024/1024/1024,1)",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "IOWait ",
     "type": "timeseries",
     "description": "IO Wait",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"iowait\"}[5m])) * 100",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "CPU Load-user",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"user\"}[5m]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"gbt-cass-11:9100\",mode =\"User\"}[5m]),1)) ) ),1) * 100",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "CPU Load-iowait",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"iowait\"}[5m]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"iowait\"}[5m]),1)) ) ),1) * 100",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "CPU Load-system",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"system\"}[5m]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"system\"}[5m]),1)) ) ),1) * 100",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"iowait\"}[5m]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"iowait\"}[5m]),1)) ) ),1) * 100",
       "legendFormat": "canon-ae-01-{{mode}}"
      },
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"system\"}[5m]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"system\"}[5m]),1)) ) ),1) * 100",
       "legendFormat": "canon-ae-01-{{mode}}"
      },
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"user\"}[5m]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode =\"User\"}[5m]),1)) ) ),1) * 100",
       "legendFormat": "canon-ae-01-{{mode}}"
      }
     ]
    },
    {
     "title": "5 min Load Average",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load5{instance=~\"localhost:9100\"}",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "15 min Load Average",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load15{instance=~\"localhost:9100\"}",
       "legendFormat": "canon-ae-01"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Reads-root",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{device=~\"xvda\",instance=\"localhost:9100\"}[5m])/1024/1024  ",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Disk Reads-ebs",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{device=~\"xvdb|xvdf\",instance=\"localhost:9100\"}[5m])/1024/1024  ",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Disk Usage-root",
     "type": "timeseries",
     "description": "Depicts LCP disk free space for / ebs volume",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",instance=\"localhost:9100\" } * 100) /  node_filesystem_size_bytes{mountpoint=\"/\",instance=\"localhost:9100\" })",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Disk Usage-ebs",
     "type": "timeseries",
     "description": "Depicts LCP disk free space for / ebs volume",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/ebs\",instance=\"localhost:9100\" } * 100) /  node_filesystem_size_bytes{mountpoint=\"/ebs\",instance=\"localhost:9100\" })",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Disk Writes-root",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_written_bytes_total{device=~\"xvda\",instance=\"localhost:9100\"}[5m])/1024/1024  ",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "Disk Writes-ebs",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_written_bytes_total{device=~\"xvdb|xvdf\",instance=\"localhost:9100\"}[5m])/1024/1024  ",
       "legendFormat": "canon-ae-01"
      }
     ]
    }
   ]
  },
  {
   "title": "Per CPU Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cpu-total",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "clamp_max(sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"localhost:9100\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"localhost:9100\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "$cpu - system",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"localhost:9100\",cpu=~\"$cpu\",mode=\"system\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"localhost:9100\",cpu=~\"$cpu\",mode=\"system\"}[$__interval]),1)) )) *100,100)",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "$cpu - other",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"localhost:9100\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"localhost:9100\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100,100)",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "$cpu-user",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"localhost:9100\",cpu=\"$cpu\",mode=\"user\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"localhost:9100\",cpu=~\"$cpu\",mode=\"user\"}[$__interval]),1)) )) *100,100)",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "$cpu - iowait",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"localhost:9100\",cpu=~\"$cpu\",mode=\"iowait\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"localhost:9100\",cpu=~\"$cpu\",mode=\"iowait\"}[$__interval]),1)) )) *100,100)",
       "legendFormat": "canon-ae-01"
      }
     ]
    },
    {
     "title": "$cpu - steel",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"localhost:9100\",cpu=~\"$cpu\",mode=\"steal\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"localhost:9100\",cpu=~\"$cpu\",mode=\"steal\"}[$__interval]),1)) )) *100,100)",
       "legendFormat": "canon-ae-01"
      }
     ]
    }
   ]
  }
 ]
}