global:
  scrape_interval:     1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  query_log_file: /ebs/prometheus/query.log

# Alertmanager configuration
alerting:
  alertmanagers:



# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /tmp/monitoring_rules/modified_rules/Linux_rules.yml
  - /tmp/monitoring_rules/modified_rules/windows_rules.yml


#To monitor the local host we cann add like this.Here 9100 is the port on which node_exporter is running.Simlarly we cann add windows exporter tooo
scrape_configs:  
  - job_name: 'localhost'
    static_configs:
    - targets: [
                'localhost:9100'
               ]
             
  - job_name: 'remote_nodes'
    static_configs:
    - targets: [
                'my-amazon-linux:9100'
               ]  

               
  #With the help of black box exporter we can monitor ssl certificates too.
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ssl_cert]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://mycert.com

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # The blackbox exporter's real hostname:port
