groups:
  - name: System_Rules
    rules:

      - record: node_memory_MemFree_percent
        expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)

      - record: node_cpu_load
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[15m])) * 100)


      - record: node_filesystem_free_percent_root
        expr: 100 * node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}

      #- record: node_filesystem_free_percent
      #  expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} * 100) /(node_filesystem_size_bytes{fstype!="tmpfs"})

      - record: node_filesystem_free_percent_ebs
        expr: 100 * node_filesystem_free_bytes{mountpoint="/ebs"} / node_filesystem_size_bytes{mountpoint="/ebs"}

      - record: node_ram_free_percent
        expr: 100 - (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=~".*"}[5m]) + avg_over_time(node_memory_Cached_bytes{job=~".*"}[5m]) + avg_over_time(node_memory_Buffers_bytes{job=~".*"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{job=~".*"}[5m]))))

  - name: System_Process_Rules
    rules:

#Platform
       - alert: P2:DiskSpaceFreePercentOnEBS_On_Platform
         expr: node_filesystem_free_percent_ebs{instance=~"canon-(h2|ilb|upl|bc2r|lcp|rules|mls)-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 180m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnEBS_On_Platform
         expr: node_filesystem_free_percent_ebs{instance=~"canon-(h2|ilb|upl|bc2r|lcp|rules|mls)-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"} <= 10
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
           
       
 #Apps      
       - alert: P2:DiskSpaceFreePercentOnEBS_On_Platform
         expr: node_filesystem_free_percent_ebs{instance=~"canon-(ui|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 180m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnEBS_On_Platform
         expr: node_filesystem_free_percent_ebs{instance=~"canon-(ui|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 10
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."      

       - alert: P2:DiskSpaceFreePercentOnRoot_On_Platform
         expr: node_filesystem_free_percent_root{instance=~"canon-(h2|ilb|upl|bc2r|lcp|rules|mls)-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 180m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnRoot_On_Platform
         expr: node_filesystem_free_percent_root{instance=~"canon-(h2|ilb|upl|bc2r|lcp|rules|mls)-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"} <= 10
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
        
        
       - alert: P2:DiskSpaceFreePercentOnRoot_On_Apps
         expr: node_filesystem_free_percent_root{instance=~"canon-(ui|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 180m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnRoot_On_Apps
         expr: node_filesystem_free_percent_root{instance=~"canon-(ui|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 10
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

#HostHighCpuUsage for  Platform
       - alert: P2:HostHighCpuUsage_On_Platform
         expr: node_cpu_load{instance=~"canon-(h2|ilb|upl|bc2r|lcp|rules)-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"} > 90
         for: 60m
         labels:
           severity: warning
           custom_alert_interval: devops
         annotations:
           summary: Host high CPU load (instance {{ $labels.instance }})
           description: "CPU load is High\n  VALUE = {{ humanize $value }}\n  LABELS = {{ $labels.instance }}"

       - alert: P2:HostHighCpuUsage_On_MLServer
         expr: node_cpu_load{instance=~"canon-mls-(01|02).ec2-east1.glassbeam.com:9100"} > 90
         for: 30m
         labels:
           severity: warning
           custom_alert_interval: ml
         annotations:
           summary: Host high CPU load (instance {{ $labels.instance }})
           description: "CPU load is High\n  VALUE = {{ humanize $value }}\n  LABELS = {{ $labels.instance }}"



#HostHighCpuUsage for apps
       - alert: P2:HostHighCpuUsage_On_apps
         expr: node_cpu_load{instance=~"canon-(ui|ums)-(01|02).ec2-east1.glassbeam.com:9100"} > 90
         for: 30m
         labels:
           severity: warning
           custom_alert_interval: apps
         annotations:
           summary: Host high CPU load (instance {{ $labels.instance }})
           description: "CPU load is High\n  VALUE = {{ humanize $value }}\n  LABELS = {{ $labels.instance }}"

#For 2 cpu nodes Platform
       - alert: P1:HostHighLoad_On_Platform_2CPU
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"canon-(ilb|upl|rules)-(01|02).ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 0.4 )* 100
           #node_load15{instance=~"canon-(ilb|upl)-(01|02).ec2-east1.glassbeam.com:9100"} > 2.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"canon-(ilb|upl)-(01|02).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"

#For 4 cpu nodes Platform
       - alert: P1:HostHighLoad_On_Platform_4CPU
         #expr: node_load15{instance=~"canon-(h2|upl|bc2r|rules)-(01|02|03).ec2-east1.glassbeam.com:9100"} > 4.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"canon-(h2|upl|bc2r|rules)-(01|02|03).ec2-east1.glassbeam.com:9100"})) > 2 )
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"canon-(h2|bc2r)-(01|02).ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 0.8 )* 100
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"

#ML
       - alert: P1:HostHighLoad_On_MLServer_4CPU
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"canon-mls-01.ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 0.8 )* 100
           #node_load15{instance=~"canon-mls-01.ec2-east1.glassbeam.com:9100"} > 8.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"canon-mls-02.ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: ml
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
           
           
           
       - alert: P1:HostHighLoad_On_MLServer_8CPU
         expr:  (avg(  sum( rate(node_cpu_seconds_total{instance=~"canon-(mls|bc2r)-(02|03).ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 1.6 )* 100
           #node_load15{instance=~"canon-mls-02.ec2-east1.glassbeam.com:9100"} > 4.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"canon-mls-02.ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: ml
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}" 



#For 8 cpu nodes Platform
       - alert: P1:HostHighLoad_On_Platform_8CPU
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"canon-lcp-(01|02|03|04|05).ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 1.6 )* 100
           #node_load15{instance=~"canon-lcp-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"} > 8.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"canon-lcp-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"

#For 2 cpu nodes apps
       - alert: P1:HostHighLoad
         expr: node_load15{instance=~"canon-ui-01.ec2-east1.glassbeam.com:9100"} > 2.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"canon-ui-01.ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: apps
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
#For 8 cpu nodes apps
       - alert: P1:HostHighLoad
         expr: node_load15{instance=~"canon-ui-02.ec2-east1.glassbeam.com:9100"} > 4.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"canon-ui-02.ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: apps
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
       - alert: P1:HostHighLoadRules_platform
         expr: node_load15{instance=~"canon-rules-(01|02).ec2-east1.glassbeam.com:9100"} > 8.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"canon-rules-(01|02).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 15m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"

#HostOutOfMemory for Platform
       - alert: P1:HostOutOfMemory_On_Platform
         expr: node_ram_free_percent{instance=~"canon-(h2|ilb|upl|bc2r|lcp|rules)-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"} <= 5
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:HostOutOfMemory_On_MLServer
         expr: node_ram_free_percent{instance=~"canon-mls-(01|02).ec2-east1.glassbeam.com:9100"} <= 5
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: ml
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."


#HostOutOfMemory for Apps
       - alert: P2:HostOutOfMemory_On_Platform
         expr: node_ram_free_percent{instance=~"canon-(h2|ilb|upl|bc2r|lcp|rules|mls)-(01|02|03|04|05).ec2-east1.glassbeam.com:9100"} <= 6 > 5
         for: 60m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

#HostOutOfMemory for Platform
       - alert: P1:HostOutOfMemory_On_Apps
         expr: node_ram_free_percent{instance=~"canon-(ui|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 5
         for: 30m
         labels:
           severity: Critical
           custom_alert_interval: apps
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P2:HostOutOfMemory_On_Apps
         expr: node_ram_free_percent{instance=~"canon-(ui|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 6 > 5
         for: 30m
         labels:
           severity: Warning
           custom_alert_interval: apps
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
