groups:

  - name: System_Rules
    rules:
      - record: node_memory_MemFree_percent
        expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)

      - record: node_cpu_load
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[15m])) * 100)

      - record: node_filesystem_free_percent_root
        expr: 100 * node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}

      #- record: node_filesystem_free_percent
      #  expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} * 100) /(node_filesystem_size_bytes{fstype!="tmpfs"})

      - record: node_filesystem_free_percent_ebs
        expr: 100 * node_filesystem_free_bytes{mountpoint="/ebs"} / node_filesystem_size_bytes{mountpoint="/ebs"}

      - record: node_ram_free_percent
        expr: 100 - (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=~".*"}[5m]) + avg_over_time(node_memory_Cached_bytes{job=~".*"}[5m]) + avg_over_time(node_memory_Buffers_bytes{job=~".*"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{job=~".*"}[5m]))))

  - name: System_Process_Rules
    rules:

       - alert: P2:DiskSpaceFreePercentOnEBS
         expr: node_filesystem_free_percent_ebs{instance=~"(gbp|canon)-(cass|kafka|solr|vert|vertops|usmesh|vnc|bst)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 480m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnEBS
         expr: node_filesystem_free_percent_ebs{instance=~"(gbp|canon)-(cass|kafka|solr|vert|vertops|usmesh|vnc|bst)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"} <= 10
         for: 480m
         labels:
           severity: Critical
           custom_alert_interval: dlmonitoring 
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
           

       - alert: P2:DiskSpaceFreePercentOnRoot
         expr: node_filesystem_free_percent_root{instance=~"(gbp|canon)-(cass|kafka|solr|vert|vertops|usmesh|vnc|bst)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 480m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnRoot
         expr: node_filesystem_free_percent_root{instance=~"(gbp|canon)-(cass|kafka|solr|vert|vertops|usmesh|vnc|bst)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"} <= 10
         for: 480m
         labels:
           severity: Critical
           custom_alert_interval: dlmonitoring
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
        
        
#HostHighCpuUsage for  Platform
       - alert: P2:HostHighCpuUsage
         expr: node_cpu_load{instance=~"(gbp|canon)-(cass|kafka|solr|vert|vertops|usmesh|vnc|bst)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"} > 90
         for: 60m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: Host high CPU load (instance {{ $labels.instance }})
           description: "CPU load is High\n  VALUE = {{ humanize $value }}\n  LABELS = {{ $labels.instance }}"
           

           
#For 2 cpu nodes Platform

       - alert: P1:HostHighLoad_On_2CPU
         expr: node_load15{instance=~"(gbp|canon)-(usmesh|vnc|bst)-(01|02).ec2-east1.glassbeam.com:9100"} > 2.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"(gbp|canon)-(usmesh|vnc)-(01|02).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m 
         labels:
           severity: Critical
           custom_alert_interval: dlmonitoring
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"


       - alert: P1:HostHighLoad_On_4CPU
         expr: node_load15{instance=~"(gbp|canon)-(kafka|solr)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"} > 4.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"(gbp|canon)-(kafka|solr)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: dlmonitoring
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
           
           
#For 16 cpu nodes Platform     
       - alert: P1:HostHighLoad_On_16CPU
         expr: node_load15{instance=~"(gbp|canon)-(cass|vert|vertops)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"} > 16.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"(gbp|canon)-(cass|vert|vertops)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: dlmonitoring
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
           

 
#HostOutOfMemory for Platform
       - alert: P1:HostOutOfMemory
         expr: node_ram_free_percent{instance=~"(gbp|canon)-(cass|kafka|solr|vert|vertops|usmesh|vnc|bst)-(01|02|03|04|06|07|08|09|10|11|12).ec2-east1.glassbeam.com:9100"} <= 5
         for: 480m
         labels:
           severity: Critical
           custom_alert_interval: dlmonitoring 
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
           
           
