groups:

  - name: System_Rules
    rules:


      - record: node_memory_MemFree_percent
        expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)

           
      - record: node_cpu_load
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[15m])) * 100)

      - record: node_filesystem_free_percent_root
        expr: 100 * node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}

      #- record: node_filesystem_free_percent
      #  expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} * 100) /(node_filesystem_size_bytes{fstype!="tmpfs"})

      - record: node_filesystem_free_percent_ebs
        expr: 100 * node_filesystem_free_bytes{mountpoint="/ebs"} / node_filesystem_size_bytes{mountpoint="/ebs"}

      - record: node_ram_free_percent
        expr: 100 - (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=~".*"}[5m]) + avg_over_time(node_memory_Cached_bytes{job=~".*"}[5m]) + avg_over_time(node_memory_Buffers_bytes{job=~".*"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{job=~".*"}[5m]))))

      - record: node_ram_without_cache_percentage
        expr: ((avg_over_time(node_memory_MemTotal_bytes[60m]) - (avg_over_time(node_memory_MemFree_bytes[60m]) + avg_over_time(node_memory_Buffers_bytes[60m]) + avg_over_time(node_memory_Cached_bytes[60m]))) / avg_over_time(node_memory_MemTotal_bytes[60m])) * 100 

  - name: System_Process_Rules
    rules:

#Platofrm
       - alert: P2:DiskSpaceFreePercentOnEBS_On_Platform
         expr: node_filesystem_free_percent_ebs{instance=~"gbp-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|mls|monitor)-(01|02|03|04|06|07|21|23).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 480m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnEBS_On_Platform
         expr: node_filesystem_free_percent_ebs{instance=~"gbp-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|monitor)-(01|02|03|04|06|07|21|23).ec2-east1.glassbeam.com:9100"} <= 10
         for: 480m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

#ML
       - alert: P1:DiskSpaceFreePercentOnEBS_On_MLServer
         expr: node_filesystem_free_percent_ebs{instance=~"gbp-mls-(01|02).ec2-east1.glassbeam.com:9100"} <= 10
         for: 480m
         labels:
           severity: Critical
           custom_alert_interval: ml
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

           
#Apps           
       - alert: P2:DiskSpaceFreePercentOnEBS_On_Platform
         expr: node_filesystem_free_percent_ebs{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 480m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnEBS_On_Platform
         expr: node_filesystem_free_percent_ebs{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 10
         for: 5m
         labels:
           severity: Critical
           custom_alert_interval: apps
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /ebs"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."           

#DiskSpaceFreePercentOnRoot
       - alert: P2:DiskSpaceFreePercentOnRoot_On_Platform
         expr: node_filesystem_free_percent_root{instance=~"gbp-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|mls|monitor)-(01|02|03|04|06|07|21|23).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 480m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnRoot_On_Platform
         expr: node_filesystem_free_percent_root{instance=~"gbp-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|monitor)-(01|02|03|04|06|07|21|23).ec2-east1.glassbeam.com:9100"} <= 10
         for: 5m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
        
#ML
       - alert: P1:DiskSpaceFreePercentOnRoot_On_MLServer
         expr: node_filesystem_free_percent_root{instance=~"gbp-mls-0(1|2).ec2-east1.glassbeam.com:9100"} <= 10
         for: 5m
         labels:
           severity: Critical
           custom_alert_interval: ml
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."



       - alert: P2:DiskSpaceFreePercentOnRoot_On_Apps
         expr: node_filesystem_free_percent_root{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 480m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOnRoot_On_Apps
         expr: node_filesystem_free_percent_root{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 10
         for: 5m
         labels:
           severity: Critical
           custom_alert_interval: apps
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /(Root)"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

#HostHighCpuUsage for  Platform
       - alert: P2:HostHighCpuUsage_On_Platform
         expr: node_cpu_load{instance=~"gbp-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|mls|monitor)-(01|02|03|04|06|07|21|23).ec2-east1.glassbeam.com:9100"} > 90
         for: 60m
         labels:
           severity: warning
           custom_alert_interval: devops
         annotations:
           summary: Host high CPU load (instance {{ $labels.instance }})
           description: "CPU load is High\n  VALUE = {{ humanize $value }}\n  LABELS = {{ $labels.instance }}"
           


#HostHighCpuUsage for apps
       - alert: P2:HostHighCpuUsage_On_apps
         expr: node_cpu_load{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"} > 90
         for: 60m
         labels:
           severity: warning
           custom_alert_interval: devops
         annotations:
           summary: Host high CPU load (instance {{ $labels.instance }})
           description: "CPU load is High\n  VALUE = {{ humanize $value }}\n  LABELS = {{ $labels.instance }}"


#For 2 cpu nodes Platform
       - alert: P1:HostHighLoad_On_Platform_2CPU
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"gbp-(bc2r|c2r|dbc2r|monitor|rules)-(01|02|03|04).ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 0.4 )* 100
           #node_load15{instance=~"gbp-(bc2r|c2r|dbc2r)-(01|02|03).ec2-east1.glassbeam.com:9100"} > 2.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"gbp-(bc2r|c2r|dbc2r)-(01|02|03).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
           
#For 4 cpu nodes Platform
       - alert: P1:HostHighLoad_On_Platform_4CPU
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"gbp-(dh2|upl|lcp|bc2r)-(01|02|03|06|07|21|23).ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 0.8 )* 100
           #node_load15{instance=~"gbp-(dh2|upl|lcp|bc2r)-(01|02|03|06|07|21|23).ec2-east1.glassbeam.com:9100"} > 4.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"gbp-(dh2|upl|lcp|bc2r)-(01|02|03|06|07|21|23).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
           
           
#For 8 cpu nodes Platform     
       - alert: P1:HostHighLoad_On_Platform_8CPU
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"gbp-monitor-03.ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 1.6 )* 100
           #node_load15{instance=~"gbp-rules-(01|02).ec2-east1.glassbeam.com:9100"} > 8.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"gbp-rules-(01|02).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
           
#For 2 cpu nodes apps
       - alert: P1:HostHighLoad
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 0.4)* 100
           #node_load15{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"} > 2.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: apps
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"
#For 4 cpu nodes apps
       - alert: P1:HostHighLoad
         expr: (avg(  sum( rate(node_cpu_seconds_total{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100", mode!="idle"}[60m])  ) without (mode) ) without (cpu) > 0.8)* 100
           #node_load15{instance=~"gbp-is-02.ec2-east1.glassbeam.com:9100"} > 4.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"gbp-is-02.ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: apps
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"

       - alert: P1:HostHighLoadRules_platform
         expr: node_load15{instance=~"gbp-rules-(01|02).ec2-east1.glassbeam.com:9100"} > 4.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"gbp-rules-(01|02).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"

#ML
#For 4 cpu nodes apps
       - alert: P1:HostHighLoad_On_MLServer_4CPU
         expr: node_load15{instance=~"gbp-mls-0(1|2).ec2-east1.glassbeam.com:9100"} > 4.0*((count without(cpu, mode) (node_cpu_seconds_total{mode="idle",instance=~"gbp-mls-0(1|2).ec2-east1.glassbeam.com:9100"})) > 2 )
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: ml
         annotations:
           summary: Host high load on (instance {{ $labels.instance }})
           description: "15 Minutes LoadAverage is High on {{ $labels.instance }} with Value: {{ humanize $value }}"

             

#HostOutOfMemory for Platform
       - alert: P1:HostOutOfMemory_On_Platform
         expr: node_ram_free_percent{instance=~"gbp-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|monitor)-(01|02|03|04|06|07|21|23).ec2-east1.glassbeam.com:9100"} <= 5
         for: 480m
         labels:
           severity: Critical
           custom_alert_interval: platform
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
           
           
       - alert: P2:HostOutOfMemory_On_Platform
         expr: node_ram_free_percent{instance=~"gbp-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|mls|monitor)-(01|02|03|04|06|07|21|23).ec2-east1.glassbeam.com:9100"} <= 10 > 5
         for: 480m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:HostOutOfMemory_On_MLServer
         expr: node_ram_free_percent{instance=~"gbp-mls-(01|02).ec2-east1.glassbeam.com:9100"} <= 5
         for: 480m
         labels:
           severity: Critical
           custom_alert_interval: ml
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."             

#HostOutOfMemory for Apps
       - alert: P2:HostOutOfMemory_On_Apps
         expr: node_ram_free_percent{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 6 > 5
         for: 480m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
       
       - alert: P1:HostOutOfMemory_On_Apps
         expr: node_ram_free_percent{instance=~"gbp-(is|ums)-(01|02).ec2-east1.glassbeam.com:9100"} <= 5
         for: 480m
         labels:
           severity: Critical
           custom_alert_interval: apps
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."                 

#HostOutOfMemoryWithoutCache
       - alert: P2:HostOutOfMemoryWithoutCache
         expr: node_ram_without_cache_percentage{instance=~"(gbp|gbt|canon)-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|mls|monitor|cass|kafka|solr|vert|vertops)-(01|02|03|04|05|06|07|08|09|10|21|23).ec2-east1.glassbeam.com:9100"}  >= 85 <= 90
         for: 60m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 15% or less Ram left "
           description: "[{{ $labels.instance }}] is using   `{{ humanize $value }}%` of Memory"

       - alert: P1:HostOutOfMemoryWithoutCache
         expr: node_ram_without_cache_percentage{instance=~"(gbp|gbt|canon)-(bc2r|c2r|dbc2r|dh2|upl|lcp|rules|mls|monitor|cass|kafka|solr|vert|vertops)-(01|02|03|04|05|06|07|08|09|10|21|23).ec2-east1.glassbeam.com:9100"}  >= 90
         for: 60m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Ram left "
           description: "[{{ $labels.instance }}] is using `{{ humanize $value }}%` of Memory"             
