groups:
  - name: Production_rules_ml
    rules:
      - alert: P1:MLCanon_AD_Process_Check
        expr: up{exported_instance="canon-mls-01.ec2-east1.glassbeam.com", exported_job="mlcanonad", job="RunningProcessStatus"} == 0
        for: 30m
        labels:
          severity: Critical
          custom_alert_interval: ml
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"


      - alert: P1:MLCanon_MLManager_Process_Check
        expr: up{exported_instance="canon-mls-02.ec2-east1.glassbeam.com", exported_job="mlmgr", job="RunningProcessStatus"} == 0
        for: 30m
        labels:
          severity: Critical
          custom_alert_interval: ml
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"

      - alert: P1:MLCommon_UED_Process_Check
        expr: up{exported_instance="gbp-mls-01.ec2-east1.glassbeam.com", exported_job="ued", job="RunningProcessStatus"} == 0
        for: 30m
        labels:
          severity: Critical
          custom_alert_interval: ml
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"

      - alert: P1:MLCommon_MLManager_Process_Check
        expr: up{exported_instance="gbp-mls-02.ec2-east1.glassbeam.com", exported_job="mlmgr", job="RunningProcessStatus"} == 0
        for: 30m
        labels:
          severity: Critical
          custom_alert_interval: ml
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"




