groups:
  - name: ssl_cert_alerts
    rules:
      - alert: P2:SSLExpiryWarning
        expr: (probe_ssl_earliest_cert_expiry - time()) >= 2592000  and  (probe_ssl_earliest_cert_expiry - time()) < 5184000

        for: 1m
        labels:
          severity: warning
          custom_alert_interval: 8h
        annotations:
          summary:  "ALERT - [SSL Certificate for {{ $labels.instance }}  is expiring in less than 60 days]"
          description: "The SSL certificate for {{ $labels.instance }} will expire in 60 days."

      - alert: P1:SSLExpiryCritical
        expr:  (probe_ssl_earliest_cert_expiry - time())  <= 2592000
        for: 1m
        labels:
          severity: critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - SSL Certificate for {{ $labels.instance }} is expiring in less than 30 days"
          description: "The SSL certificate for {{ $labels.instance }} will expire in 30 days."

      - alert: SSLDown
        expr: probe_http_ssl == 0  # Adjust this based on how your `probe_http_ssl` metric indicates a failure
        for: 1m
        labels:
          severity: critical
          custom_alert_interval: devops
        annotations:
          summary: "SSL Certificate for {{ $labels.instance }} is down"
          description: "The SSL certificate for {{ $labels.instance }} is not valid or has expired."
