groups:
  - name: gb4gb_Process_Rules
    rules:
      - alert: P2:GB4GB_SBX_Kafka_Process_Check
        expr: up{exported_job=~"kafka",exported_instance=~"gb4gb-sbx-01.ec2-east1.glassbeam.com"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"

      - alert: P2:GB4GB_SBX_Kafka_ZooKeeper_Process_Check
        expr: up{exported_job=~"kafka_zk",exported_instance=~"gb4gb-sbx-01.ec2-east1.glassbeam.com"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"

      - alert: P2:GB4GB_SBX_Cassandra_Process_Check
        expr: up{exported_job=~"cassandra",exported_instance=~"gb4gb-sbx-01.ec2-east1.glassbeam.com"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"

      - alert: P2:GB4GB_LCPBatchRules_Process_Check
        expr: up{exported_job=~"lcprules",exported_instance=~"gb4gb-(lcp|sbx)-01.ec2-east1.glassbeam.com"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"

      - alert: P2:LCP_AE_Process_Check
        expr: up{exported_job=~"lcpae",exported_instance=~"gb4gb-lcp-01.ec2-east1.glassbeam.com"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"            

      - alert: P2:GB4GB_Process_Check
        expr: up{exported_job=~"gbforgb",exported_instance=~"gb4gb-lcp-01.ec2-east1.glassbeam.com"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"

      - alert: P2:GB4GB_SchemaManager_Process_Check
        expr: up{exported_job=~"sm",exported_instance=~"gb4gb-(lcp|sbx)-01.ec2-east1.glassbeam.com"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"

      - alert: P2:GB4GB_NodeExporter_Process_Check
        expr: up{instance=~"gb4gb-(lcp|sbx)-01.ec2-east1.glassbeam.com:9100"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - [{{ $labels.instance }}] / [ {{ $labels.job }} ]:CRITICAL"
          description: "The NodeExporter Process is down"

      - alert: P2:GB4GB_SSHD_Process_Check
        expr: up{exported_job=~"sshd",exported_instance=~"gb4gb-.*"} == 0
        for: 1m
        labels:
          severity: Critical
          custom_alert_interval: devops
        annotations:
          summary: "ALERT - SSHD_Process_Check:CRITICAL"
          description: "The SSHD_Process_Check is down on {{ $labels.exported_instance }}"
