groups:
  - name: System_Rules
    rules:
      - record: node_filesystem_free_percent_tmp
        expr: 100 * node_filesystem_free_bytes{mountpoint="/tmp"} / node_filesystem_size_bytes{mountpoint="/tmp"}
        
      - record: node_filesystem_free_percent_var
        expr: 100 * node_filesystem_free_bytes{mountpoint="/var"} / node_filesystem_size_bytes{mountpoint="/var"}
        
        
  - name: System_Process_Rules
    rules:
       - alert: P2:DiskSpaceFreePercentOnVAR
         expr: node_filesystem_free_percent_var{instance=~"(gbp|canon|gbt|gb4gb)-(h2|dh2|ilb|upl|lcp|bc2r|c2r|dbc2r|rules|ui|ums|is|monitor)-(01|02|03|04|06|07|08|09|10|11|12|21|23).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 5m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /var"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOVAR
         expr: node_filesystem_free_percent_var{instance=~"(gbp|canon|gbt|gb4gb)-(h2|dh2|ilb|upl|lcp|bc2r|c2r|dbc2r|rules|ui|ums|is|monitor)-(01|02|03|04|06|07|08|09|10|11|12|21|23).ec2-east1.glassbeam.com:9100"} <= 10
         for: 5m
         labels:
           severity: Critical
           custom_alert_interval: dlmonitoring
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /var"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."



       - alert: P2:DiskSpaceFreePercentOnTMP
         expr: node_filesystem_free_percent_tmp{instance=~"(gbp|canon|gbt|gb4gb)-(h2|dh2|ilb|upl|lcp|bc2r|c2r|dbc2r|rules|ui|ums|is|monitor)-(01|02|03|04|06|07|08|09|10|11|12|21|23).ec2-east1.glassbeam.com:9100"} <= 20 > 10
         for: 5m
         labels:
           severity: Warning
           custom_alert_interval: devops
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 20% or less Free disk space at /tmp"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:DiskSpaceFreePercentOTMP
         expr: node_filesystem_free_percent_tmp{instance=~"(gbp|canon|gbt|gb4gb)-(h2|dh2|ilb|upl|lcp|bc2r|c2r|dbc2r|rules|ui|ums|is|monitor)-(01|02|03|04|06|07|08|09|10|11|12|21|23).ec2-east1.glassbeam.com:9100"} <= 10
         for: 5m
         labels:
           severity: Critical
           custom_alert_interval: dlmonitoring
         annotations:
           summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space at /tmp"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

       - alert: P1:CHRONYDServiceCheck
         expr: up{exported_instance="(gbp|canon|gbt|gb4gb)-(h2|dh2|ilb|upl|lcp|bc2r|c2r|dbc2r|rules|ui|ums|is|monitor)-(01|02|03|04|06|07|08|09|10|11|12|21|23).ec2-east1.glassbeam.com", exported_job="chronyd"} == 0
         for: 1m
         labels:
           severity: Critical
           custom_alert_interval: devops
         annotations:
          summary: "ALERT - [{{ $labels.exported_instance }}] / [ {{ $labels.exported_job }} ]:CRITICAL"
          description: "[ {{ $labels.exported_job }} ] Process is down"
           
