 - name: System_Rules
    rules:
      - record: windows_node_cpu_load
        expr: 100 - avg by(instance) (rate(windows_cpu_time_total{mode="idle"}[15m])) * 100

      - record: Windows_node_memory_MemFree_percent
        expr: 100 - (1 - windows_os_physical_memory_free_bytes / windows_os_visible_memory_bytes) * 100

           
      - record: node_cpu_load
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[15m])) * 100)

      - record: node_free_percent_C_Drive
        expr: 100 * (windows_logical_disk_free_bytes{volume="C:"} / windows_logical_disk_size_bytes{volume="C:"})

      - record: node_free_percent_D_Drive
        expr: 100 * (windows_logical_disk_free_bytes{volume="D:"} / windows_logical_disk_size_bytes{volume="D:"})



      - record: node_ram_free_percent
        expr: 100 - (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=~".*"}[5m]) + avg_over_time(node_memory_Cached_bytes{job=~".*"}[5m]) + avg_over_time(node_memory_Buffers_bytes{job=~".*"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{job=~".*"}[5m]))))

  - name: System_Process_Rules
    rules:
#WindowsHighCpuUsage
       - alert: P2:WindowsHighCpuUsage
         expr: windows_node_cpu_load{instance=~"aws_windows:9182"} > 80 <90
         for: 2m
         labels:
           severity: warning
           custom_alert_interval: naveen
         annotations:
           summary: "High CPU Usage on {{ $labels.instance }}"
           description: "CPU load is High\n  VALUE = {{ humanize $value }}\n  LABELS = {{ $labels.instance }}"

       - alert: P1:WindowsCpuUsage
         expr: windows_node_cpu_load{instance=~"aws_windows:9182"} > 90
         for: 2m
         labels:
           severity: Critical
           custom_alert_interval: naveen
         annotations:
           summary:  "High CPU Usage on {{ $labels.instance }}"
           description: "CPU load is High\n  VALUE = {{ humanize $value }}\n  LABELS = {{ $labels.instance }}"
           
#DiskSpaceFreePercent_C_Drive           
       - alert: P2:DiskSpaceFreePercent_C_Drive
         expr: node_free_percent_C_Drive{instance=~"aws_windows:9182"} > 80 < 90
         for: 2m
         labels:
           severity: Warning
           custom_alert_interval: naveen
         annotations:
           summary: "Instance {{ $labels.instance }} has 20% or less Free disk space on C_Drive"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."
       
       - alert: P1:DiskSpaceFreePercent_C_Drive
         expr: node_free_percent_C_Drive{instance=~"aws_windows:9182"} > 90
         for: 2m
         labels:
           severity: Critical
           custom_alert_interval:  naveen
         annotations:
           summary: "Instance {{ $labels.instance }} has 10% or less Free disk space on C_Drive"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

#DiskSpaceFreePercent_D_Drive        
       - alert: P2:DiskSpaceFreePercent_D_Drive
         expr: node_free_percent_D_Drive{instance=~"aws_windows:9182"} >= 80 <90
         for: 2m
         labels:
           severity: Warning
           custom_alert_interval: naveen
         annotations:
           summary: "Instance {{ $labels.instance }} has 20% or less Free disk space on D_Drive"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."          

       - alert: P1:DiskSpaceFreePercent_D_Drive
         expr: node_free_percent_D_Drive{instance=~"aws_windows:9182"} > 90
         for: 2m
         labels:
           severity: Critical
           custom_alert_interval: naveen
         annotations:
           summary: "Instance {{ $labels.instance }} has 20% or less Free disk space on D_Drive"
           description: "[{{ $labels.instance }}] has only `{{ humanize $value }}%` or less free."

#WindowsOutOfMemory           
       - alert: P2:WindowsOutOfMemory
         expr: Windows_node_memory_MemFree_percent{instance=~"aws_windows:9182"} >= 80 < 90 
         for: 2m
         labels:
           severity: Warning
           custom_alert_interval: naveen
         annotations:
           summary: "Instance {{ $labels.instance }} has 20% or less Ram left "
           description: "{{ $labels.instance }} has only `{{ humanize $value }}%` or less free."

       - alert: P1:WindowsOutOfMemory
         expr: Windows_node_memory_MemFree_percent{instance=~"aws_windows:9182"} >= 90
         for: 2m
         labels:
           severity: Critical
           custom_alert_interval: naveen
         annotations:
           summary: "Instance {{ $labels.instance }} has 10% or less Ram left "
           description: "{{ $labels.instance }} has only `{{ humanize $value }}%` or less free."

             
#Node_exporter check 
       - alert: P2:NodeExporter_Process_Check
         expr: up{instance=~"aws_windows:9182"} == 0
         for: 2m
         labels:
           severity: Critical
           custom_alert_interval: naveen
         annotations:
           summary: "ALERT - [{{ $labels.instance }}] / [ {{ $labels.job }} ]:CRITICAL"
           description: "The NodeExporter Process is down"

